# Configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file

version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - maven-google
    open-pull-requests-limit: 10
    groups:
      kotlin-compose:
        patterns:
          - "androidx.compose.*"
          - "androidx.glance*"
          - "org.jetbrains.kotlin*"
          - "io.coil-kt:coil-compose"
          - "com.android.tools.build:gradle"
          - "androidx.activity:activity-compose"
          - "androidx.lifecycle:lifecycle-viewmodel-compose"
      ktor:
        patterns:
          - "io.ktor*"
      google-firebase:
        patterns:
          - "com.google*"
          - "com.android.billingclient*"
      kotest:
        patterns:
          - "io.kotest*"
      androidx:
        patterns:
          - "androidx.*"
      hilt:
        patterns:
          - "com.google.dagger*"
          - "androidx.hilt*"
      room:
        patterns:
          - "androidx.room*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

# This is only a workaround as long as
# https://github.com/dependabot/dependabot-core/pull/7260
# is not merged
registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
