name: 'Gradle Wrapper Upgrade'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  upgrade-gradle-wrapper:
    runs-on: ubuntu-latest
    env:
      WRAPPER_UPGRADE_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global url."https://unused-username:${WRAPPER_UPGRADE_GIT_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Upgrade Gradle Wrapper
        run: ./gradlew upgradeGradleWrapperIvyWallet
